{% set name = "oxasl_ve" %}
{% set version = "0.2.0.post3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oxasl-ve-{{ version }}.tar.gz
  sha256: 7fc3472ad311cbe1c4321a3cf9aca459aa15ce289a7bd6d8c15507911a15db18

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fslpy >=1.13
    - numpy
    - oxasl
    - python >=3.6

test:
  imports:
    - oxasl_ve
    - oxasl_ve.wrappers

about:
  home: https://oxasl.readthedocs.io/
  summary: Python library for manipulating and modelling ASL data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mcraig-ibme
